# 这是一个基础的 GitHub Actions 工作流模板，帮助你快速上手

name: CI  # 工作流名称（持续集成）

# 控制工作流的触发条件
on:
  # 以下事件会触发工作流：
  # 1. 向 main 分支推送代码时
  # 2. 针对 main 分支创建拉取请求时
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # 允许从 GitHub Actions 页面手动触发此工作流
  workflow_dispatch:

# 工作流由多个作业(job)组成，这些作业可以串行或并行执行
jobs:
  # 本工作流包含一个名为 "build" 的作业
  build:
    # 指定运行此作业的 Runner 类型
    runs-on: ubuntu-24.04  # 使用最新版 Ubuntu 系统

    # 步骤(steps)定义了作业中按顺序执行的任务序列
    steps:
      # 第一步：检出仓库代码到工作目录 ($GITHUB_WORKSPACE)
      - uses: actions/checkout@v4  # 使用官方检出 Action

      # 第二步：在 Runner 的 shell 中执行单行命令
      - name: 运行单行脚本  # 步骤名称
        run: echo Hello, world!  # 输出欢迎信息

      # 第三步：执行多行命令
      - name: 运行多行脚本
        run: |  # 通过 | 符号定义多行命令
          echo 添加其他操作来构建、
          echo 测试并部署你的项目。
      
      # 第四步:安装g++编译器

      - name: 安装 g++ 编译器
        run: sudo apt-get install g++

      # 第五步:编译并运行代码
      - name: 编译并运行代码
        run: |
          g++ -o main main.cpp  # 编译 hello.cpp 文件
          ./main  # 运行编译后的程序